# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 18:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageWelcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Home Page Welcome',
            },
        ),
    ]
